#!/bin/bash

## SET CMD LINE VARS
setvar () {
    while [[ $# -gt 0 ]]
    do
        export $1
        shift
    done
}

## FIND PREFIX FROM EXECUTABLE
prefixer() {
    ppath=""
    if which $1 &> /dev/null; then
        ppath="$(dirname $(dirname $(which $1)))"
    fi
}

mpif=$MPI_HOME
if [ -z $mpif ]; then mpif=${CRAY_MPICH_PREFIX}; fi
if [ -z $mpif ]; then mpif=$(prefixer mpicc); fi

export CC=cc
export CXX=CC
export FC=ftn
export F90=ftn
export MPICH_GPU_SUPPORT_ENABLED=1
export MPILD=$CXX
export MPICC=$CC
export MPI_HOME=$mpif
MAKEIT=

ngpu=$(nvidia-smi -q | awk '/Attach/ {print $NF}')
topx=4
topy=2
srun_opts=

###############################################################
## OVERRIDE THE DEFAULT ARGUMENTS WITH COMMAND LINE OPTIONS
###############################################################

setvar $@

###############################################################
## GET SRUN OPTIONS
###############################################################
--exclude=nid001897,nid001765
nprcs=$(( topx*topy ))
snn=$(( nprcs/ngpu ))

cd src
if [[ -n $MAKEIT ]]; then
	make clean
	make 
fi

cd ../rslt

echo NORMAL $topx $topy $snn $nprcs
echo "srun -N $snn --ntasks-per-node=${ngpu} ${srun_opts} ./run_mpi ../bin/jacobi_cuda_normal_mpi -t $topx $topy"
srun -N $snn --ntasks-per-node=${ngpu} ${srun_opts} ./run_mpi ../bin/jacobi_cuda_normal_mpi -t $topx $topy

if [[ -f core ]]; then mv core core_normal; echo CORE_NORMAL; fi

echo AWARE
echo "srun -N $snn --ntasks-per-node=4${ngpu} ${srun_opts} ./run_mpi ../bin/jacobi_cuda_aware_mpi -t $topx $topy"
srun -N $snn --ntasks-per-node=${ngpu} ${srun_opts} ./run_mpi ../bin/jacobi_cuda_aware_mpi -t $topx $topy

if [[ -f core ]]; then mv core core_aware; echo CORE_AWARE; fi

cd ..
