#!/bin/bash

## SET CMD LINE VARS
setvar () {
    while [[ $# -gt 0 ]]
    do
        export $1
        shift
    done
}

separator() {
    echo "######################################################"
}

## FIND PREFIX FROM EXECUTABLE
prefixer() {
    ppath=""
    if which $1 &> /dev/null; then
        ppath="$(dirname $(dirname $(which $1)))"
    fi
}

mpif=$MPI_HOME
if [ -z $mpif ]; then mpif=${CRAY_MPICH_PREFIX}; fi
if [ -z $mpif ]; then mpif=$(prefixer mpicc); fi

export CC=cc
export CXX=CC
export FC=ftn
export F90=ftn
export MPICH_GPU_SUPPORT_ENABLED=1
export MPILD=$CXX
export MPICC=$CC
export MPI_HOME=$mpif
export CUDA_HOME=${CUDA_HOME:-$CUDA_PATH}
export NNODES=$SLURM_NNODES
export SRUN_OPTS=""
MAKEIT=
CUDA_COMPAT="${CUDA_HOME}/compat"

ngpu=$(nvidia-smi -q | awk '/Attach/ {print $NF}')
topy=4
topx=4

###############################################################
## OVERRIDE THE DEFAULT ARGUMENTS WITH COMMAND LINE OPTIONS
###############################################################

setvar $@
srun_opts="-N ${NNODES} --ntasks-per-node=${ngpu} ${SRUN_OPTS}" #Add defaults here.

###############################################################
## GET TOPOLOGY
###############################################################

: ${topx=:$ngpu}
: ${topy=:NNODES}

###############################################################
## MAKE AND RUN
###############################################################
cd src
if [[ -d $CUDA_COMPAT ]]; then
    if [[ ! ("${LD_LIBRARY_PATH}" =~ "${CUDA_COMPAT}") ]]; then
		export LD_LIBRARY_PATH="${CUDA_COMPAT}:${LD_LIBRARY_PATH}"
    fiq
    export CUDA_COMPAT
fi

if [[ -n $MAKEIT ]]; then
    separator
    echo "MAKING..."
	make clean
	make
    echo ""
fi

cd ../rslt

separator
echo NORMAL $topx $topy $snn $nprcs
separator
echo "srun ${srun_opts} ./run_mpi ../bin/jacobi_cuda_normal_mpi -t $topx $topy"
srun ${srun_opts} ./run_mpi ../bin/jacobi_cuda_normal_mpi -t $topx $topy

if [[ -f core ]]; then mv core core_normal; echo CORE_NORMAL; fi

separator
echo AWARE
separator
echo "srun ${srun_opts} ./run_mpi ../bin/jacobi_cuda_aware_mpi -t $topx $topy"
srun ${srun_opts} ./run_mpi ../bin/jacobi_cuda_aware_mpi -t $topx $topy

if [[ -f core ]]; then mv core core_aware; echo CORE_AWARE; fi

cd ..
