#!/bin/bash

noderank=${OMPI_COMM_WORLD_LOCAL_RANK:-$SLURM_LOCALID}
mpirank=${PMIX_RANK:-$SLURM_PROCID}
nr=$(( $noderank+1 ))
export CUDA_VISIBLE_DEVICES=$noderank

if [[ $1 == "dbg" ]]; then
	shift
	echo "DEBUG"
	echo "cuda-gdb --args $@"
	if [[ $mpirank == 0 ]]; then	
		cuda-gdb --args $@
	else
		$@
	fi
else
	$@
fi
